# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.define "syslog1" do |syslog|
    syslog.vm.box = "ubuntu/xenial64"
      syslog.vm.hostname = "syslog1"
      syslog.vm.network "private_network", ip:"192.168.33.30"
  end

  config.vm.define "web1" do |web|
    web.vm.box = "ubuntu/xenial64"
      web.vm.hostname = "web1"
      web.vm.network "private_network", ip: "192.168.33.31"
  end

  config.vm.define "lb1" do |lb|
    lb.vm.box = "ubuntu/xenial64"
      lb.vm.hostname = "lb1"
      lb.vm.network "private_network", ip: "192.168.33.32"
  end
end
